Skr/general fixes and improvements
tiacsys/bridle-tutorials pull request #1
Opened 2024-10-04 16:27 UTC by skratochwil-inovex

Some rewording, refinement, fixed URLs, and more precise formulations. Chapter '0040-fw-gpio-led-btn' is incomplete, chapter '0050-hw-setup-usb-console' is entirely untouched. Build and look-and-feel are tested locally.

No changes to the overall structure so far, since this requires some coordination.

2024-11-08 09:09 UTC, skratochwil-inovex commented
Hi @rexut,
I just saw that this PR is still open. Did you have some time to review it?

2024-11-09 07:55 UTC, rexut commented
> Hi @rexut, I just saw that this PR is still open. Did you have some time to review it?

Hi @skratochwil-inovex, unfortunately still not. I've been busy porting Bridle to Zephyr upstream v4.0.0 since Vienna. I haven't had the chance to do a review in my limited spare time. But I have already had a rough look over it. Looks good. Thank you.

I'm sure I'll get around to something more over the Christmas time. Hopefully it won't take so long. But I want to do it right in the course of this review and build up a pipeline. So far, this tutorial is still being built and deployed manually. This is totally impractical, as neither of us can see whether these changes are still "officially" being built.

2024-12-02 17:51 UTC, rexut requested changes
Finally, the time has come. I have time for a review.

Thank you very much for your helpful revision and improvement. I will gladly adopt your formulations and also transfer them to other parts of the instructions. So please don't be surprised if I now take over the PR branch and also create a rebase. The only “formal” note: the commit messages (subject) do not follow the rules of “conventional commits” as described in our [CONTRIBUTING.md “Get Started!”](https://github.com/tiacsys/bridle-tutorials/blob/main/CONTRIBUTING.md#get-started).

The statement “Request changes” only refers to the formal note, not the content. I would now like to take up your input.

2024-12-02 20:11 UTC, rexut commented
Now closed. Further development on PR #2 – @skratochwil-inovex: do not use your private fork. As member of the TiaC Sys Dev-Team you can write directly to this repository.

2024-12-02 20:11 UTC, closed without merging